
--1. Find all persons with their department name & code. 

	SELECT PERSONNAME,DEPARTMENTCODE FROM PERSON INNER JOIN DEPARTMENT ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID;

--2. Give department wise maximum & minimum salary with department name.

	SELECT DEPARTMENTNAME,MIN(SALARY)AS MINIMUM,MAX(SALARY)AS MAXIMUM FROM DEPARTMENT INNER JOIN PERSON ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
	GROUP BY DEPARTMENTNAME;

--3. Find all departments whose total salary is exceeding 100000.

	SELECT DEPARTMENTNAME,SUM(SALARY) FROM DEPARTMENT INNER JOIN PERSON ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
	GROUP BY DEPARTMENTNAME
	HAVING SUM(SALARY)>100000;

--4. Retrieve person name, salary & department name who belongs to Jamnagar city.

	SELECT PERSONNAME,SALARY,DEPARTMENTNAME FROM DEPARTMENT INNER JOIN PERSON ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID 
	WHERE CITY='JAMNAGAR';

--5. Find all persons who does not belongs to any department.

	SELECT PERSONNAME FROM PERSON WHERE DEPARTMENTID IS NULL;

--6. Find department wise person counts.

	SELECT COUNT(PERSONID),DEPARTMENTNAME FROM DEPARTMENT INNER JOIN PERSON ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
	GROUP BY DEPARTMENTNAME;

--7. Find average salary of person who belongs to Ahmedabad city.
	
	SELECT AVG(SALARY),CITY FROM DEPARTMENT INNER JOIN  PERSON ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
	GROUP BY CITY;

--8. Produce Output Like: <PersonName> earns <Salary> from department <DepartmentName> monthly.

	SELECT PERSON.PERSONNAME + 'EARNS' + CAST(SALARY AS VARCHAR) +'DEPARTMENT' + DEPARTMENT.DEPARTMENTNAME + 'MONTHLY'
	FROM DEPARTMENT INNER JOIN PERSON ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID;

--9. List all departments who have no persons.

	SELECT DEPARTMENTNAME,COUNT(PERSONID) FROM DEPARTMENT INNER JOIN  PERSON ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
	GROUP BY DEPARTMENTNAME
	HAVING COUNT(PERSONID)=0;

--10. Find city & department wise total, average & maximum salaries.

	SELECT DEPARTMENTNAME,SUM(SALARY) AS TOTAL,AVG(SALARY) AS AVERAGE,MAX(SALARY) AS MAXIMUM FROM DEPARTMENT INNER JOIN  PERSON ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
	GROUP BY DEPARTMENTNAME;

	SELECT CITY,SUM(SALARY) AS TOTAL,AVG(SALARY) AS AVERAGE,MAX(SALARY) AS MAXIMUM FROM DEPARTMENT INNER JOIN  PERSON ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
	GROUP BY CITY;

--11. Display Unique city names.

	SELECT DISTINCT(CITY) FROM PERSON;

--12. List out department names in which more than two persons.

	SELECT DEPARTMENTNAME,COUNT(PERSONID) AS PERSON FROM DEPARTMENT INNER JOIN  PERSON ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
	GROUP BY DEPARTMENTNAME
	HAVING COUNT(PERSONID)>2;

--13. Combine person name’s first three characters with city name’s last three characters in single column.

	SELECT SUBSTRING(PERSONNAME,1,3)+' '+SUBSTRING(CITY,LEN(CITY)-2,3) AS NAME FROM PERSON;
	
	SELECT LEFT (PersonName,3) + RIGHT (city,3) FROM Person;

--14. Give 10% increment in Computer department employee’s salary.

	UPDATE PERSON SET SALARY = (SALARY*10)/100 + SALARY
	WHERE DEPARTMENTID = (SELECT DEPARTMENTID FROM DEPARTMENT WHERE DEPARTMENTNAME = 'COMPUTER');

--15. Display all the person name’s who’s joining dates difference with current date is more than 365 days.	SELECT PersonName FROM Person 
	WHERE (GETDATE()-JoiningDate)>365;